[package]
name = "lfg-support"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "~0.1"
lfg-core = { path = "../core" }
tokio = { version = "1.0", features = ["full"] }
